### ISSUE TITLE
Relicense as MIT?

### ISSUE THREAD

**Issue by msmollin** [peterent/SwiftUICharts#1]
Hi! I came across this looking for a decent SwiftUI charting library. I was thinking about using it in my app but I saw you licensed this as GPL-3. Any chance you'd mind re-licensing to something App Store compatible (MIT, BSD, Apache, etc.)?

**Comment by peterent** [comment]
I am so sorry for the delay. I must have missed the license type I intended. I hope you have gone ahead and used it. I never think to look at my GitHub notice; I will now.

**Comment by peterent** [comment]
The license was changed to an MIT license. Thanks for letting me know.
